### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by mbtaylor12** [meziantou/Meziantou.OneDrive#1]
Would it be possible to update the usage section of the readme? It seems the package has evolved over three years but the usage section has not. In particular, the CredentialManagerRefreshTokenHandler constructor has new required parameters and CreateFileAsync also has new parameters.

**Comment by meziantou** [comment]
Hi,

Thanks for the feedback! I've updated the sample of `CredentialManagerRefreshTokenHandler` to use the new constructor. I use Meziantou.OneDrive in another project, so you can check the code to see how to use it: [Meziantou.Backup](https://github.com/meziantou/Meziantou.Backup/tree/master/Meziantou.Backup.FileSystem.OneDrive), [CreateFileAsync](https://github.com/meziantou/Meziantou.Backup/blob/677fe0a0b650f941033ece72c889ab120164e48b/Meziantou.Backup.FileSystem.OneDrive/OneDriveFileInfo.cs#L59)
